# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7339f63404880dbb167206f6c75b730bc512d63874760e87e2b1ce2cf6f1668527625ce2fad6000854df9c5a7edec0efa2d5263b3c93c38ee770c8cad4f7638f

test:
  secret_key_base: 31d5a85b36b9322d21a7dcf655ef1e8557930c6a5c15e38d6479b6eb70d7660fb16e794faf9f92a7ddd015e0e3ffd3c1e86703fbaf4c45764b772900ae827b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
