# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

CreativeEscape.create(skill: "Dog Mushing School", description: "Dream of driving your own dog sled? This half day mushing adventure is for you. Learn the role of each dog in the team and practice the basics of sled handling. Meet your very own team of sled dogs before setting out on a five-mile journey through Alaska's winter wonderland. Minimum age to drive is 18 years old and moderate fitness level highly recommended.", length: "one day", price: 399, currency: "USD", streetnumber: 1401, address: "W 9th Ave", postcode: "99501", city: "Anchorage", country: "USA", email: "mushingschool@gmail.com", phone: 8449, bookable: false)
CreativeEscape.create(skill: "Mindful Cooking Retreat", description: "Together we’ll learn how to practice mindfulness while cooking and preparing food; how to cultivate healthy eating habits, as well as cultivating joy as nourishment, both for ourselves and our loved ones. This week-long retreat is based on the requests of many friends who have been to New Hamlet and have enjoyed the meals so much that they are inspired to become vegetarians or vegan after their retreat. You will be shown step by step how to prepare some popular Vietnamese dishes that are much loved at New Hamlet. You will have a chance to practice sitting meditation, walking meditation, eating in silence, doing exercises, listening to Dharma talks, practicing noble silence, sharing in families, and learning the art of mindful cooking.", length: "one week", price: 550, currency: "EUR", streetnumber: 13, address: "Martineau", postcode: "33580", city: "Dieulivol", country: "France", email: "nh-office@plumvillage.org", phone:3305, bookable: true)
CreativeEscape.create(skill: "Paros Writers Retreat", description: "Writers will reside in a charming Cycladic-styled hotel set amongst lush gardens on a hillside overlooking the Aegean sea. All rooms have sea and sunset views from their own private balconies and there are plentiful public and private places in the hotel and on the lush grounds for reflective writing time in the numerous furnished indoor and outdoor lounge areas and garden patios overlooking the swimming pool and the sea. Morning breakfasts will be included and served at the hotel before adjourning to a nearby private seaside villa where the Writing Workshops will be held overlooking the sea and where there are again plentiful private scenic spots for reading and writing and discussion.", length: "one week", price: 1495, currency: "USD", address: "Cyclades", postcode: "84400", city: "Paros", country: "Greece", email: "info@RogueDogPress.com", phone: 6988, bookable: true)
CreativeEscape.create(skill: "Weekend Crafting Retreat", description: "The Craft Sessions Annual Retreat is a weekend retreat of creative workshops, delicious food, quiet moments and inspiring people. It is an opportunity to play and learn, to talk, and share ideas. It’s about coming together and sharing a love of making, appreciating the beauty in the smaller things, and delighting in the pleasure and simplicity of all things handmade. The weekend is an opportunity to immerse yourself in a weekend knitting, weaving, stitching, printing, sewing, dyeing and making. Surrounded by beautiful greenery, the retreat spaces boasts big light filled rooms with stunning views of the surrounding bush.", length: "2.5 days", price: 895, currency: "AUD", city: "Melbourne", country: "Australia", email: "thecraftsessions@gmail.com", bookable: true)
CreativeEscape.create(skill: "Silver Jewellery Making", description: "One of the first to open special classes for those who wish to learn the art of silver jewellery making in Ubud, Chez Monique on Jalan Dewi Sita lets you master the craft in only a couple of hours. Founded by Balinese silver craftsman Wayan Sunarta, who also oversees the classes and lends a bit of silversmith mentoring to participants, Chez Monique provides a different way to experience your Bali holiday. Classes usually take four hours, during which you can create your own unique jewellery piece. You may opt to follow one design from their simple yet stylish design collection, and Wayan’s three staff will help you to accomplish your first mission. You can make a gorgeous ring, exotic bracelet, stunning necklace or earrings. Moreover, any crazy design ideas that you might have are met with open arms. Chez Monique’s showroom is located on Jalan Dewi Sita, while the classes are taught on Wayan’s own family compound on Jalan Sriwedari Taman.", length: "half day", price: 50, currency: "USD", streetnumber: 36, address: "Jl. Hanoman", postcode: "8057", city: "Ubud", country: "Indonesia", email: "www.chezmoniquejewelry.com", phone: 9813, bookable: false)
