# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


CreativeEscape.create(length: "between 8 hours and 30 hours",skill: "embroidery", description: "Maison Lesage Lesage has been creating opulent embroidery requiring countless hours of work and exceptional skills for Haute Couture, Ready-to-Wear and accessories since its creation in 1924. The company founded an embroidery school in 1992 that welcomes those who are passionate about embroidery from all over the world.
Lesage became part of CHANEL’s Métiers d’art in 2002.", price: 1350 , currency: "euros" , streetnumber: 13, address: "rue de la Grange Batelière" , postcode: 75009, city:"Paris" , email: "contact@lesage.fr" , phone: 0471335125 , bookable: false, country: "France" )

CreativeEscape.create(length: "nine weeks", skill: "coding", description: "Le Wagon is rated 1st coding bootcamp in the world according to Coursereport and Switchup.We have taught more than 1430 student and our program has evolved each time to reach perfection. We believe building a great curriculum takes time and it took us nearly 3 years to design the FullStack program. It is our longstanding experience that makes our program so efficient. You will learn in 2 months what you would have learned in 2 years", price: 4900, currency: "euros" , streetnumber: 5 , address:"Sinter-Goedelevoorplein", postcode: 1000, city: "Brussels", email: "contact@lewagon.com", phone:  0471334202, bookable: false, country: "Belgium")

CreativeEscape.create(length: "between a week and 8 weeks", skill: "Vegan Cuisine", description: "Matthew Kenney Culinary offers students a special opportunity to complete a series of programs and receive seals that mark major accomplishments in their culinary education. In order for students to be awarded CORE and MASTER seal program recognition all courses must be successfully completed as listed below. Speak with our admissions team about special Master Seal Program pricing. Upon completion of required courses students will receive an electronic seal for placement on website or CV to honor their achievements.", price: 4000, currency: "euros", streetnumber: 51 , address: "Casa de Camp", postcode: 1200, city: "Barcelona", email: "plantlab@gmail.com", phone: 0532512012, bookable: false, country: "Spain")

CreativeEscape.create(length: "8 days",skill: "beer brewing", description: "Micro Malting in Practice is an 8-day full-time hands-on course providing up-to-date knowledge in the field of malting. It covers the basics of malting technology in theory and practice. The lectures will cover topics such as malting barley and other relevant cereals (botanics, quality, varieties, enzymes a.o.), malting technology (steeping, germination, kilning, special aspects of small-scale malting, equipment) and practical laboratory work (barley and malt analysis, interpretation and assessment of different quality parameters).
In addition, the participants will conduct and accompany a complete malting batch in our pilot malting.
The language is English. You can expect an intensive training with maximum benefit.", price: 1990, currency: "euros", streetnumber: 13, address: "Seestrasse", postcode: 13533, city: "Berlin", email: "beer@vlbberlin.org", phone: 0223526352 , bookable: true, country: "Germany" )

c = CreativeEscape.create(length: "2 days", skill: "silk screen printing", description: "Print Club London: Join one of our amazing designers who will guide you through all aspects of screen print design and teach you how to create a professional, 2 colour edition.
Over the course of 2 days you will be taught all the tricks and skills you need to start screen printing independently at a high level. Day 1 kicks off in the Print Club Gallery (next door to the Print Club studio) in Dalston. You will be taught the building blocks of artwork creation through the use of examples, learning step by step how all the different effects are achieved.
With the small class size, there will be lots of time for the tutor to discuss with you the best way to achieve an amazing print from the starting point of your design. Once all the artwork has been created and prepared for print, you will be taught how to coat, expose and wash out your screens ready for day 2!
Day 2 is all about the printing… In the morning you will be shown different types of ink, how to mix up your inks and print your first layer. In the afternoon everyone  will print their second layers. After all the printing is done, and you’ve had a chance to admire your newly taught printing prowess, you will be shown how to blast out your screen!", price: 160, currency: "pounds", streetnumber: 10, address: "Print Club London Millers Avenue", postcode:"D82DS", city: "London", email: "london@gmail.com", phone: 0212412541 , bookable: true, country: "United Kingdom")


#EscapePhoto.create(creative_escape: c, )

CreativeEscape.create(skill: "Dog Mushing School", description: "Dream of driving your own dog sled? This half day mushing adventure is for you. Learn the role of each dog in the team and practice the basics of sled handling. Meet your very own team of sled dogs before setting out on a five-mile journey through Alaska's winter wonderland. Minimum age to drive is 18 years old and moderate fitness level highly recommended.", length: "one day", price: 399, currency: "USD", streetnumber: 1401, address: "W 9th Ave", postcode: "99501", city: "Anchorage", country: "USA", email: "mushingschool@gmail.com", phone: 8449, bookable: false)
CreativeEscape.create(skill: "Mindful Cooking Retreat", description: "Together we’ll learn how to practice mindfulness while cooking and preparing food; how to cultivate healthy eating habits, as well as cultivating joy as nourishment, both for ourselves and our loved ones. This week-long retreat is based on the requests of many friends who have been to New Hamlet and have enjoyed the meals so much that they are inspired to become vegetarians or vegan after their retreat. You will be shown step by step how to prepare some popular Vietnamese dishes that are much loved at New Hamlet. You will have a chance to practice sitting meditation, walking meditation, eating in silence, doing exercises, listening to Dharma talks, practicing noble silence, sharing in families, and learning the art of mindful cooking.", length: "one week", price: 550, currency: "EUR", streetnumber: 13, address: "Martineau", postcode: "33580", city: "Dieulivol", country: "France", email: "nh-office@plumvillage.org", phone:3305, bookable: true)
CreativeEscape.create(skill: "Paros Writers Retreat", description: "Writers will reside in a charming Cycladic-styled hotel set amongst lush gardens on a hillside overlooking the Aegean sea. All rooms have sea and sunset views from their own private balconies and there are plentiful public and private places in the hotel and on the lush grounds for reflective writing time in the numerous furnished indoor and outdoor lounge areas and garden patios overlooking the swimming pool and the sea. Morning breakfasts will be included and served at the hotel before adjourning to a nearby private seaside villa where the Writing Workshops will be held overlooking the sea and where there are again plentiful private scenic spots for reading and writing and discussion.", length: "one week", price: 1495, currency: "USD", address: "Cyclades", postcode: "84400", city: "Paros", country: "Greece", email: "info@RogueDogPress.com", phone: 6988, bookable: true)
CreativeEscape.create(skill: "Weekend Crafting Retreat", description: "The Craft Sessions Annual Retreat is a weekend retreat of creative workshops, delicious food, quiet moments and inspiring people. It is an opportunity to play and learn, to talk, and share ideas. It’s about coming together and sharing a love of making, appreciating the beauty in the smaller things, and delighting in the pleasure and simplicity of all things handmade. The weekend is an opportunity to immerse yourself in a weekend knitting, weaving, stitching, printing, sewing, dyeing and making. Surrounded by beautiful greenery, the retreat spaces boasts big light filled rooms with stunning views of the surrounding bush.", length: "2.5 days", price: 895, currency: "AUD", city: "Melbourne", country: "Australia", email: "thecraftsessions@gmail.com", bookable: true)
CreativeEscape.create(skill: "Silver Jewellery Making", description: "One of the first to open special classes for those who wish to learn the art of silver jewellery making in Ubud, Chez Monique on Jalan Dewi Sita lets you master the craft in only a couple of hours. Founded by Balinese silver craftsman Wayan Sunarta, who also oversees the classes and lends a bit of silversmith mentoring to participants, Chez Monique provides a different way to experience your Bali holiday. Classes usually take four hours, during which you can create your own unique jewellery piece. You may opt to follow one design from their simple yet stylish design collection, and Wayan’s three staff will help you to accomplish your first mission. You can make a gorgeous ring, exotic bracelet, stunning necklace or earrings. Moreover, any crazy design ideas that you might have are met with open arms. Chez Monique’s showroom is located on Jalan Dewi Sita, while the classes are taught on Wayan’s own family compound on Jalan Sriwedari Taman.", length: "half day", price: 50, currency: "USD", streetnumber: 36, address: "Jl. Hanoman", postcode: "8057", city: "Ubud", country: "Indonesia", email: "www.chezmoniquejewelry.com", phone: 9813, bookable: false)
